import type {
  Alert,
  AppUserRecord,
  ChecklistItem,
  Chemical,
  ChemTx,
  Equipment,
  Incident,
  Maintenance,
  OpLog,
  Threshold,
} from "./types";

export const CHECKLIST_ITEMS: ChecklistItem[] = [
  "Đo pH nước đầu vào và các bể bằng máy đo pH.",
  "Căn chỉnh lưu lượng khí cung cấp cho bể sục khí phù hợp để điều chỉnh nồng độ Oxy hòa tan.",
  "Vệ sinh các Hố thu gom, giỏ, lưới chắn rác khu A, Khu B, bể xử lý.",
  "Ghi chỉ số đồng hồ lưu lượng nước thải đầu vào, đầu ra để tính lưu lượng nước thải phát sinh trong giờ cao điểm.",
  "Xử lý bùn nổi ở Bể lắng.",
  "Vệ sinh thiết bị đo lưu lượng.",
  "Kiểm tra bùn vi sinh trong các bể xử lý, chỉ số bùn.",
  "Kiểm tra đèn tín hiệu, phao, timer, đèn sự cố.",
  "Kiểm tra sự tắc nghẽn, van, và đầu hút của bơm.",
  "Kiểm tra và khắc phục mùi hôi phát sinh (nếu có) từ hệ thống xử lý nước thải.",
  "Kiểm tra chế độ vận hành.",
  "Kiểm tra bồn lọc, rửa lọc.",
  "Kiểm tra, vệ sinh Hố thu gom tại khu B.",
  "Kiểm tra, vệ sinh lưới chắn rác tại hệ thống XLNT 220m³/ngày.",
  "Kiểm tra, vệ sinh lưới chắn rác tại hệ thống XLNT 600m³/ngày.",
  "Kiểm tra, vệ sinh lưới chắn giá thể tại các bể sinh học.",
  "Vệ sinh bùn nổi Bể lắng và cân chỉnh thu bùn bề mặt Bể lắng.",
  "Kiểm tra và pha hóa chất hàng ngày.",
  "Kiểm tra vệ sinh tấm lắng lamen.",
].map((Noi_dung, i) => ({
  Item_ID: `CKL-${String(i + 1).padStart(2, "0")}`,
  Noi_dung,
  Thu_tu: i + 1,
  Kich_hoat: true,
}));

export const SEED_USERS: AppUserRecord[] = [
  {
    User_ID: "UMC-USR-MSN-ADMIN",
    Email: "msn@admin.local",
    Ho_ten: "Mà Song Nguyễn",
    So_dien_thoai: "",
    Don_vi: "Ban Giám Đốc",
    Ghi_chu: "Tài khoản quản lý — đăng ký / đăng nhập email (msn@admin.local)",
    Vai_tro: "QUAN_LY",
    Trang_thai: "HOAT_DONG",
    Ngay_tao: "2026-08-19",
  },
  {
    User_ID: "UMC-USR-20260715-0001",
    Email: "masongnguyen@gmail.com",
    Ho_ten: "Mà Song Nguyễn",
    So_dien_thoai: "0900000000",
    Don_vi: "Ban Giám Đốc",
    Ghi_chu: "Tài khoản quản lý khởi tạo hệ thống — tab USERS",
    Vai_tro: "QUAN_LY",
    Trang_thai: "HOAT_DONG",
    Ngay_tao: "2026-07-15",
  },
  {
    User_ID: "UMC-USR-20260719-0002",
    Email: "dainam@umc.edu.vn",
    Ho_ten: "Nguyễn Văn Thành",
    So_dien_thoai: "0903000102",
    Don_vi: "Công ty Đại Nam",
    Ghi_chu: "Giám sát nhà thầu tại chỗ — phục vụ phân quyền NHA_THAU",
    Vai_tro: "NHA_THAU",
    Trang_thai: "HOAT_DONG",
    Ngay_tao: "2026-07-19",
  },
  {
    User_ID: "UMC-USR-20260719-0003",
    Email: "catruc@umc.edu.vn",
    Ho_ten: "Trần Thị Hoa",
    So_dien_thoai: "0903000103",
    Don_vi: "Công ty Đại Nam",
    Ghi_chu: "Vận hành ca trực 7h–18h — phục vụ phân quyền CA_TRUC",
    Vai_tro: "CA_TRUC",
    Trang_thai: "HOAT_DONG",
    Ngay_tao: "2026-07-19",
  },
];

export const SEED_THRESHOLDS: Threshold[] = [
  {
    Threshold_ID: "TH-LU-01",
    Ma_nguong: "NT_NGAY_THUONG",
    Ten_nguong: "Lưu lượng xả thải ngày thường",
    Nhom: "LUU_LUONG",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 810,
    Gia_tri_2: null,
    Muc_do: "CRITICAL",
    Kich_hoat: true,
    Ghi_chu: "Ngưỡng ngày thường T2–T6. Bám sát thực tế 2022–2023 (max 818).",
  },
  {
    Threshold_ID: "TH-LU-02",
    Ma_nguong: "NT_CUOI_TUAN",
    Ten_nguong: "Lưu lượng xả thải cuối tuần",
    Nhom: "LUU_LUONG",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 650,
    Gia_tri_2: null,
    Muc_do: "CRITICAL",
    Kich_hoat: true,
    Ghi_chu: "Ngưỡng cuối tuần T7–CN",
  },
  {
    Threshold_ID: "TH-LU-03",
    Ma_nguong: "HE220_KHOANG",
    Ten_nguong: "Lưu lượng vận hành hệ 220",
    Nhom: "LUU_LUONG",
    He_thong: "He_220",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 200,
    Gia_tri_2: 220,
    Muc_do: "WARNING",
    Kich_hoat: true,
    Ghi_chu: "Khoảng lưu lượng an toàn hệ 220",
  },
  {
    Threshold_ID: "TH-LU-04",
    Ma_nguong: "HE600_MAX",
    Ten_nguong: "Giới hạn lưu lượng hệ 600",
    Nhom: "LUU_LUONG",
    He_thong: "He_600",
    Toan_tu: ">",
    Gia_tri_1: 600,
    Gia_tri_2: null,
    Muc_do: "CRITICAL",
    Kich_hoat: true,
    Ghi_chu: "Giới hạn lưu lượng hệ 600",
  },
  {
    Threshold_ID: "TH-LU-05",
    Ma_nguong: "CHENH_CAP_THAI",
    Ten_nguong: "Chênh lệch nước cấp và thải",
    Nhom: "LUU_LUONG",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 140,
    Gia_tri_2: null,
    Muc_do: "HIGH",
    Kich_hoat: true,
    Ghi_chu: "Độ chênh lệch tối đa Cấp − Thải",
  },
  {
    Threshold_ID: "TH-LU-06",
    Ma_nguong: "THAT_THOAT_B",
    Ten_nguong: "Thất thoát nước khu B",
    Nhom: "LUU_LUONG",
    He_thong: "Nuoc_cap",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: -5,
    Gia_tri_2: 5,
    Muc_do: "HIGH",
    Kich_hoat: true,
    Ghi_chu: "Độ thất thoát Khu B cho phép",
  },
  {
    Threshold_ID: "TH-CL-01",
    Ma_nguong: "SV30_HE600",
    Ten_nguong: "SV30 hệ 600",
    Nhom: "CHAT_LUONG",
    He_thong: "He_600",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 300,
    Gia_tri_2: 400,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 300–400 ml/L (Báo cáo T04/2026)",
  },
  {
    Threshold_ID: "TH-CL-02",
    Ma_nguong: "SV30_HE220",
    Ten_nguong: "SV30 hệ 220",
    Nhom: "CHAT_LUONG",
    He_thong: "He_220",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 250,
    Gia_tri_2: 350,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải 250–350 ml/L. Cận dưới 250 phủ quy tắc E-HSMT bùn hoạt tính thấp.",
  },
  {
    Threshold_ID: "TH-CL-03",
    Ma_nguong: "PH_IN_HE600",
    Ten_nguong: "pH đầu vào hệ 600",
    Nhom: "CHAT_LUONG",
    He_thong: "He_600",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 7.0,
    Gia_tri_2: 7.5,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 7,0–7,5",
  },
  {
    Threshold_ID: "TH-CL-04",
    Ma_nguong: "PH_IN_HE220",
    Ten_nguong: "pH đầu vào hệ 220",
    Nhom: "CHAT_LUONG",
    He_thong: "He_220",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 7.0,
    Gia_tri_2: 7.5,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 7,0–7,5",
  },
  {
    Threshold_ID: "TH-CL-05",
    Ma_nguong: "PH_OUT_HE600",
    Ten_nguong: "pH đầu ra hệ 600",
    Nhom: "CHAT_LUONG",
    He_thong: "He_600",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 7.2,
    Gia_tri_2: 7.6,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 7,2–7,6",
  },
  {
    Threshold_ID: "TH-CL-06",
    Ma_nguong: "PH_OUT_HE220",
    Ten_nguong: "pH đầu ra hệ 220",
    Nhom: "CHAT_LUONG",
    He_thong: "He_220",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 7.0,
    Gia_tri_2: 7.4,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 7,0–7,4",
  },
  {
    Threshold_ID: "TH-CL-07",
    Ma_nguong: "AMONI_HE600",
    Ten_nguong: "Amoni hệ 600",
    Nhom: "CHAT_LUONG",
    He_thong: "He_600",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 5.0,
    Gia_tri_2: 8.0,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 5,0–8,0 mg/l",
  },
  {
    Threshold_ID: "TH-CL-08",
    Ma_nguong: "AMONI_HE220",
    Ten_nguong: "Amoni hệ 220",
    Nhom: "CHAT_LUONG",
    He_thong: "He_220",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 3.0,
    Gia_tri_2: 6.0,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 3,0–6,0 mg/l",
  },
  {
    Threshold_ID: "TH-CL-09",
    Ma_nguong: "COD_HE600",
    Ten_nguong: "COD hệ 600",
    Nhom: "CHAT_LUONG",
    He_thong: "He_600",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 30,
    Gia_tri_2: 40,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 30–40",
  },
  {
    Threshold_ID: "TH-CL-10",
    Ma_nguong: "COD_HE220",
    Ten_nguong: "COD hệ 220",
    Nhom: "CHAT_LUONG",
    He_thong: "He_220",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 10,
    Gia_tri_2: 20,
    Muc_do: "NHAC_NHO",
    Kich_hoat: true,
    Ghi_chu: "Dải vận hành 10–20",
  },
  {
    Threshold_ID: "TH-PL-01",
    Ma_nguong: "QCVN_PH",
    Ten_nguong: "pH nước thải sau xử lý",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: "OUT_OF_RANGE",
    Gia_tri_1: 6.5,
    Gia_tri_2: 8.5,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B, K=1",
  },
  {
    Threshold_ID: "TH-PL-02",
    Ma_nguong: "QCVN_BOD5",
    Ten_nguong: "BOD5",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 50,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 50 mg/l",
  },
  {
    Threshold_ID: "TH-PL-03",
    Ma_nguong: "QCVN_COD",
    Ten_nguong: "COD",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 100,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 100 mg/l",
  },
  {
    Threshold_ID: "TH-PL-04",
    Ma_nguong: "QCVN_TSS",
    Ten_nguong: "Tổng chất rắn lơ lửng (TSS)",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 100,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 100 mg/l",
  },
  {
    Threshold_ID: "TH-PL-05",
    Ma_nguong: "QCVN_AMONI",
    Ten_nguong: "Amoni (tính theo N)",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 10,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 10 mg/l",
  },
  {
    Threshold_ID: "TH-PL-06",
    Ma_nguong: "QCVN_PHOTPHAT",
    Ten_nguong: "Photphat (tính theo P)",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 10,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 10 mg/l",
  },
  {
    Threshold_ID: "TH-PL-07",
    Ma_nguong: "QCVN_NITRAT",
    Ten_nguong: "Nitrat (tính theo N)",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 50,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 50 mg/l",
  },
  {
    Threshold_ID: "TH-PL-08",
    Ma_nguong: "QCVN_DAUMO",
    Ten_nguong: "Dầu mỡ động thực vật",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 20,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 20 mg/l",
  },
  {
    Threshold_ID: "TH-PL-09",
    Ma_nguong: "QCVN_SUNFUA",
    Ten_nguong: "Sunfua (tính theo H2S)",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 4,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 4 mg/l",
  },
  {
    Threshold_ID: "TH-PL-10",
    Ma_nguong: "QCVN_COLIFORM",
    Ten_nguong: "Tổng Coliform",
    Nhom: "PHAP_LY",
    He_thong: "Nuoc_thai",
    Toan_tu: ">",
    Gia_tri_1: 5000,
    Gia_tri_2: null,
    Muc_do: "LOI",
    Kich_hoat: true,
    Ghi_chu: "QCVN 28:2010 cột B: ≤ 5.000 MPN/100ml",
  },
];

export const SEED_CHEMICALS: Chemical[] = [
  {
    Ma_hoa_chat: "NAOH",
    Ten_hoa_chat: "NaOH ≥98%",
    Don_vi_tinh: "kg",
    Nguong_canh_bao_ton: null,
    Dinh_muc_thang_van_hanh: 567,
    Dinh_muc_he600: 416,
    Dinh_muc_he220: 151,
    Khoi_luong_hopdong_18thang: 11250,
    Ghi_chu: "Cân bằng pH. Hợp đồng 5.2 quy đổi ≈ 625 kg/tháng.",
  },
  {
    Ma_hoa_chat: "JAVEN",
    Ten_hoa_chat: "Javen 10%",
    Don_vi_tinh: "kg",
    Nguong_canh_bao_ton: null,
    Dinh_muc_thang_van_hanh: 1047,
    Dinh_muc_he600: 914,
    Dinh_muc_he220: 133,
    Khoi_luong_hopdong_18thang: 22447,
    Ghi_chu: "Khử trùng. Hợp đồng 5.2 quy đổi ≈ 1.247 kg/tháng.",
  },
  {
    Ma_hoa_chat: "NAHCO3",
    Ten_hoa_chat: "NaHCO3",
    Don_vi_tinh: "kg",
    Nguong_canh_bao_ton: null,
    Dinh_muc_thang_van_hanh: 180,
    Dinh_muc_he600: 132,
    Dinh_muc_he220: 48,
    Khoi_luong_hopdong_18thang: 3240,
    Ghi_chu: "Ổn định pH. Hợp đồng khớp định mức vận hành 180 kg/tháng.",
  },
  {
    Ma_hoa_chat: "MATRI",
    Ten_hoa_chat: "Mật rỉ đường",
    Don_vi_tinh: "kg",
    Nguong_canh_bao_ton: null,
    Dinh_muc_thang_van_hanh: 750,
    Dinh_muc_he600: 550,
    Dinh_muc_he220: 200,
    Khoi_luong_hopdong_18thang: 13500,
    Ghi_chu: "Tăng carbon cho vi sinh. Hợp đồng khớp 750 kg/tháng.",
  },
  {
    Ma_hoa_chat: "VISINH",
    Ten_hoa_chat: "Vi sinh xử lý nước thải",
    Don_vi_tinh: "gallon",
    Nguong_canh_bao_ton: null,
    Dinh_muc_thang_van_hanh: null,
    Dinh_muc_he600: null,
    Dinh_muc_he220: null,
    Khoi_luong_hopdong_18thang: 108,
    Ghi_chu:
      "Hạng mục hợp đồng mới. 108 gallon/18 tháng. Bacillus, Clostridium, Desulfovibrio, Pseudomonas, Rhodopseudomonas.",
  },
];

export const SEED_STOCKS: Record<string, number> = {
  NAOH: 0,
  JAVEN: 0,
  NAHCO3: 0,
  MATRI: 0,
  VISINH: 0,
};

export const SEED_TX: ChemTx[] = [];

type EqSrc = [string, string, "He_600" | "He_220", string, string, number, string, string];

const EQP_SRC: EqSrc[] = [
  ["TB-600-01", "Bơm thu gom và điều hòa", "He_600", "EBARA", "DW VOX-300", 3, "Bơm chìm, Q=100–180 l/phút, cột áp 15,7–3,6 mH2O, P=2,2kW, inox", "Lý lịch v2: Q=100–800 l/phút (GPMT ghi 100–180)"],
  ["TB-600-02", "Bơm bùn bể lắng & bể nén bùn", "He_600", "EBARA", "DW VOX-300", 5, "Bơm chìm, Q=100–180 l/phút, cột áp 15,7–3,6 mH2O, P=2,2kW, inox", "Lý lịch v2: Q=100–800 l/phút (GPMT ghi 100–180)"],
  ["TB-600-03", "Bơm lọc", "He_600", "", "", 3, "Bơm chìm, Q=100–180 l/phút, cột áp 15,7–3,6 mH2O, P=2,2kW, inox", "Chưa xác minh model — chủng loại GPMT vs lý lịch mâu thuẫn"],
  ["TB-600-04", "Máy thổi khí bể điều hòa", "He_600", "ANLET", "BH-65", 2, "Root, Q=1,28 m³/phút, cột áp 5100mmAq, P=5,5kW, 1700rpm", "P=5,5kW theo GPMT + lý lịch (báo cáo T04 ghi 4kW)"],
  ["TB-600-05", "Máy thổi khí bể hiếu khí có giá thể", "He_600", "ANLET", "BS-80", 3, "Root, Q=4,06 m³/phút, cột áp 5100mmAq, P=5,5kW, 1300rpm", ""],
  ["TB-600-06", "Bơm định lượng Chlorine", "He_600", "", "", 2, "Bơm màng, Q=30 l/h, cột áp 30 PSI, P=45W", "Đã xác nhận 16/07/2026: 45W đúng (GPMT ghi 45KW là lỗi đánh máy)"],
  ["TB-600-07", "Máy khuấy hóa chất", "He_600", "DOLIN", "SH 12-12", 1, "Chân đế, tốc độ 1/15–1/90, P=0,4kW", ""],
  ["TB-600-08", "Máy khuấy chìm", "He_600", "FAGGIOLATI", "GM-18", 2, "Root, P=1,3kW, 1370 v/phút", ""],
  ["TB-600-09", "Đĩa tán khí bể điều hòa", "He_600", "", "", 16, "Mịn, Q=5-26 m³/giờ, Ø127mm", ""],
  ["TB-600-10", "Đĩa phân phối khí", "He_600", "", "", 67, "Mịn, Q=0-8 m³/giờ, Ø277mm", ""],
  ["TB-600-11", "Thiết bị khống chế lưu lượng", "He_600", "", "", 1, "Thùng inox, Q=20-30 m³/giờ", ""],
  ["TB-600-12", "Tấm trợ lắng", "He_600", "", "", 28, "Vách nghiêng, 62 m²/m³", "SL = 28 m³ (đơn vị thể tích)"],
  ["TB-600-13", "Ống lắng trung tâm", "He_600", "", "", 1, "Q=15-25 m³/h", ""],
  ["TB-600-14", "Lược rác (song chắn rác)", "He_600", "", "", 1, "Q=15-30 m³/h, inox", ""],
  ["TB-600-15", "Bồn hóa chất", "He_600", "", "", 2, "PE 4 lớp, 500L", ""],
  ["TB-600-16", "Bồn lọc áp lực", "He_600", "", "", 4, "Q=20-30m³/h, cát 0,4-1,2mm cao 80cm + sỏi 2-4mm cao 30cm", "4 bộ"],
  ["TB-220-01", "Bơm nước thải (nhóm 1)", "He_220", "ZENIT", "DGO200/2/G50V", 3, "P=1,5kW, cột áp 6,9, Q=25m³/h", ""],
  ["TB-220-02", "Bơm nước thải (nhóm 2)", "He_220", "ZENIT", "DGO75/2/G50V", 7, "P=0,55kW, cột áp 6, Q=9,2m³/h", "GPMT gộp 7 bơm = 3 nhóm lý lịch cùng model"],
  ["TB-220-03", "Bơm lọc", "He_220", "EBARA", "3D32-160/2.2", 3, "P=2,2kW, cột áp 30, Q=12m³/h", "Q=12m³/h theo GPMT + lý lịch"],
  ["TB-220-04", "Máy khuấy chìm", "He_220", "FAGGIOLATI", "GM17A471T1-4V2KA0", 2, "P=0,7kW, 380V 3 pha, Ø cánh 176mm", ""],
  ["TB-220-05", "Máy thổi khí (nhóm 1)", "He_220", "TOHIN", "HC-501S", 2, "P=2,2kW, cột áp 4, Q=1,36 m³/phút", ""],
  ["TB-220-06", "Máy thổi khí (nhóm 2)", "He_220", "TOHIN", "HC-100S", 2, "P=5,5kW, cột áp 4, Q=4,18 m³/phút", ""],
  ["TB-220-07", "Đĩa thổi khí", "He_220", "", "", 21, "Mịn, Q=0-16 m³/giờ", ""],
  ["TB-220-08", "Thiết bị đo oxy hòa tan", "He_220", "", "", 1, "Thang đo 0-20mg/l, độ phân giải 0,01", ""],
  ["TB-220-09", "Thiết bị đo pH", "He_220", "", "", 1, "Thang đo 0-14, độ phân giải 0,01", ""],
  ["TB-220-10", "Phao đo mức (sóng siêu âm)", "He_220", "", "", 1, "", ""],
  ["TB-220-11", "Phao đo mức nước", "He_220", "", "", 6, "Chịu áp 1 bar", ""],
  ["TB-220-12", "Mô tơ khuấy hóa chất", "He_220", "NORD", "SK01F-71L4", 2, "P=0,37kW, 100-150 rpm", ""],
  ["TB-220-13", "Thiết bị gạt bùn", "He_220", "", "", 1, "P=0,37kW, 0,1 rpm", ""],
  ["TB-220-14", "Bơm định lượng", "He_220", "MILTON ROY", "GM0025 PRIMNN", 6, "Q=25 l/h, đẩy 12 bar/hút 2 bar", ""],
  ["TB-220-15", "Đồng hồ đo lưu lượng", "He_220", "", "", 1, "PN16, DN50", ""],
  ["TB-220-16", "Quạt hút mùi", "He_220", "", "", 1, "Q=3500 m³/giờ, áp tĩnh 3000Pa, 10HP", "Chưa xác minh model so với lý lịch Đại Phong"],
  ["TB-220-17", "Bồn lọc áp lực", "He_220", "", "", 2, "Q=9,2m³/h, cát+sỏi như hệ 600", "2 bộ"],
  ["TB-220-18", "Bơm hố thu gom hệ 220", "He_220", "EBARA", "DW VOX-300", 3, "Bơm chìm, P=2,2kW", "Xác nhận thực địa 16/07/2026 — không có trong GPMT Bảng 5"],
];

export const SEED_EQUIPMENTS: Equipment[] = EQP_SRC.map((r) => ({
  Equipment_ID: r[0],
  Ten_thiet_bi: r[1],
  He_thong: r[2],
  Hang_SX: r[3],
  Model: r[4],
  So_luong: r[5],
  Thong_so: r[6],
  Tinh_trang: "HOAT_DONG",
  Ghi_chu: r[7],
}));

export const SEED_INCIDENTS: Incident[] = [
  {
    Incident_ID: "INC-EQP-20251122-0001",
    Equipment_ID: "TB-600-02",
    Ngay_phat_sinh: "2025-11-22",
    Mo_ta_su_co: "Bơm bùn 3 (hệ 600): đế bơm bung mối hàn. Nguyên nhân: bơm rung lâu ngày.",
    Bien_phap_xu_ly: "Thay bơm dự phòng.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-11-24",
  },
  {
    Incident_ID: "INC-EQP-20251225-0002",
    Equipment_ID: "TB-220-18",
    Ngay_phat_sinh: "2025-12-25",
    Mo_ta_su_co:
      "Bơm nước thải khu B (hệ 220): bơm cháy do vô nước. Xác nhận thực địa 16/07/2026: bơm hố thu khu B thuộc hệ 220.",
    Bien_phap_xu_ly: "Thay bơm dự phòng.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-12-26",
  },
  {
    Incident_ID: "INC-EQP-20260105-0003",
    Equipment_ID: "TB-600-02",
    Ngay_phat_sinh: "2026-01-05",
    Mo_ta_su_co: "Bơm bùn 5 (hệ 600): bơm cháy. Nguyên nhân: bơm bị vô nước.",
    Bien_phap_xu_ly: "Thay bơm dự phòng.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2026-01-06",
  },
  {
    Incident_ID: "INC-EQP-20251106-0004",
    Equipment_ID: "TB-220-16",
    Ngay_phat_sinh: "2025-11-06",
    Mo_ta_su_co: "Quạt hút mùi (hệ 220): kêu to. Cánh quạt đứt mối hàn, niểng cánh.",
    Bien_phap_xu_ly: "Hàn, cân chỉnh cánh.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-11-06",
  },
  {
    Incident_ID: "INC-EQP-20251220-0005",
    Equipment_ID: "TB-220-02",
    Ngay_phat_sinh: "2025-12-20",
    Mo_ta_su_co: "Bơm tuần hoàn 1 (hệ 220): mòn cánh và buồng bơm. Vật liệu gang ăn mòn.",
    Bien_phap_xu_ly: "Thay mới cánh + buồng bơm.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-12-28",
  },
  {
    Incident_ID: "INC-EQP-20251220-0006",
    Equipment_ID: "TB-220-02",
    Ngay_phat_sinh: "2025-12-20",
    Mo_ta_su_co: "Bơm tuần hoàn 2 (hệ 220): mòn cánh và buồng bơm.",
    Bien_phap_xu_ly: "Thay mới cánh + buồng bơm.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-12-28",
  },
  {
    Incident_ID: "INC-EQP-20251220-0007",
    Equipment_ID: "TB-220-02",
    Ngay_phat_sinh: "2025-12-20",
    Mo_ta_su_co: "Bơm bùn 1 (hệ 220): mòn cánh và buồng bơm.",
    Bien_phap_xu_ly: "Thay mới cánh + buồng bơm.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-12-29",
  },
  {
    Incident_ID: "INC-EQP-20251220-0008",
    Equipment_ID: "TB-220-02",
    Ngay_phat_sinh: "2025-12-20",
    Mo_ta_su_co: "Bơm bùn 2 (hệ 220): mòn cánh và buồng bơm.",
    Bien_phap_xu_ly: "Thay mới cánh + buồng bơm.",
    Trang_thai: "DA_XU_LY",
    Nguoi_khac_phuc: "Công ty Đại Nam",
    Ngay_hoan_thanh: "2025-12-29",
  },
];

export const SEED_MAINT: Maintenance[] = [
  {
    Maint_ID: "MNT-EQP-202604-0001",
    Equipment_ID: "TB-600-05",
    Ngay_bao_tri: "",
    Ket_qua: "DAT_YEU_CAU",
    Noi_dung_bao_tri: "Thay phốt và bạc đạn máy thổi khí AB-03 hệ 600. Đã lắp lại, hoạt động ổn định.",
    Vat_tu_thay_the: "Phốt, bạc đạn",
    Ghi_chu: "T04/2026. Nguồn chỉ ghi tháng — Ngay_bao_tri để trống.",
  },
  {
    Maint_ID: "MNT-EQP-202604-0002",
    Equipment_ID: "TB-600-05",
    Ngay_bao_tri: "",
    Ket_qua: "DAT_YEU_CAU",
    Noi_dung_bao_tri: "Thay phốt và bạc đạn máy thổi khí AB-05 hệ 600. Đã lắp lại, hoạt động ổn định.",
    Vat_tu_thay_the: "Phốt, bạc đạn",
    Ghi_chu: "T04/2026. Nguồn chỉ ghi tháng — Ngay_bao_tri để trống.",
  },
];

export const SEED_LOGS: OpLog[] = [];

export const SEED_ALERTS: Alert[] = [];

export const CONFIGS_DEFAULT: Record<string, string> = {
  SYS_NAME: "Hệ thống Vận hành Trạm XLNT UMC",
  CONTRACTOR_NAME: "Công ty Đại Nam",
  MAINTENANCE_MODE: "false",
  DESIGN_CAPACITY: "820",
  CSDL_NAME: "UMC - Cơ sở dữ liệu vận hành Trạm XLNT",
  CSDL_VERSION: "v7-20260716",
};
