/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiLuuLuongRouteImport } from './routes/api/luu-luong'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAiRouteImport } from './routes/app/ai'
import { Route as AppBaocaoRouteImport } from './routes/app/baocao'
import { Route as AppCanhbaoRouteImport } from './routes/app/canhbao'
import { Route as AppHoachatRouteImport } from './routes/app/hoachat'
import { Route as AppNguongRouteImport } from './routes/app/nguong'
import { Route as AppNhatkyRouteImport } from './routes/app/nhatky'
import { Route as AppNhatkySoRouteImport } from './routes/app/nhatky-so'
import { Route as AppQuantriRouteImport } from './routes/app/quantri'
import { Route as AppTheodoiRouteImport } from './routes/app/theodoi'
import { Route as AppThietbiRouteImport } from './routes/app/thietbi'
import { Route as AppTrienkhaiRouteImport } from './routes/app/trienkhai'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLuuLuongRoute = ApiLuuLuongRouteImport.update({
  id: '/api/luu-luong',
  path: '/api/luu-luong',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppBaocaoRoute = AppBaocaoRouteImport.update({
  id: '/baocao',
  path: '/baocao',
  getParentRoute: () => AppRoute,
} as any)
const AppCanhbaoRoute = AppCanhbaoRouteImport.update({
  id: '/canhbao',
  path: '/canhbao',
  getParentRoute: () => AppRoute,
} as any)
const AppHoachatRoute = AppHoachatRouteImport.update({
  id: '/hoachat',
  path: '/hoachat',
  getParentRoute: () => AppRoute,
} as any)
const AppNguongRoute = AppNguongRouteImport.update({
  id: '/nguong',
  path: '/nguong',
  getParentRoute: () => AppRoute,
} as any)
const AppNhatkyRoute = AppNhatkyRouteImport.update({
  id: '/nhatky',
  path: '/nhatky',
  getParentRoute: () => AppRoute,
} as any)
const AppNhatkySoRoute = AppNhatkySoRouteImport.update({
  id: '/nhatky-so',
  path: '/nhatky-so',
  getParentRoute: () => AppRoute,
} as any)
const AppQuantriRoute = AppQuantriRouteImport.update({
  id: '/quantri',
  path: '/quantri',
  getParentRoute: () => AppRoute,
} as any)
const AppTheodoiRoute = AppTheodoiRouteImport.update({
  id: '/theodoi',
  path: '/theodoi',
  getParentRoute: () => AppRoute,
} as any)
const AppThietbiRoute = AppThietbiRouteImport.update({
  id: '/thietbi',
  path: '/thietbi',
  getParentRoute: () => AppRoute,
} as any)
const AppTrienkhaiRoute = AppTrienkhaiRouteImport.update({
  id: '/trienkhai',
  path: '/trienkhai',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/luu-luong': typeof ApiLuuLuongRoute
  '/app/ai': typeof AppAiRoute
  '/app/baocao': typeof AppBaocaoRoute
  '/app/canhbao': typeof AppCanhbaoRoute
  '/app/hoachat': typeof AppHoachatRoute
  '/app/nguong': typeof AppNguongRoute
  '/app/nhatky': typeof AppNhatkyRoute
  '/app/nhatky-so': typeof AppNhatkySoRoute
  '/app/quantri': typeof AppQuantriRoute
  '/app/theodoi': typeof AppTheodoiRoute
  '/app/thietbi': typeof AppThietbiRoute
  '/app/trienkhai': typeof AppTrienkhaiRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/luu-luong': typeof ApiLuuLuongRoute
  '/app/ai': typeof AppAiRoute
  '/app/baocao': typeof AppBaocaoRoute
  '/app/canhbao': typeof AppCanhbaoRoute
  '/app/hoachat': typeof AppHoachatRoute
  '/app/nguong': typeof AppNguongRoute
  '/app/nhatky': typeof AppNhatkyRoute
  '/app/nhatky-so': typeof AppNhatkySoRoute
  '/app/quantri': typeof AppQuantriRoute
  '/app/theodoi': typeof AppTheodoiRoute
  '/app/thietbi': typeof AppThietbiRoute
  '/app/trienkhai': typeof AppTrienkhaiRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/luu-luong': typeof ApiLuuLuongRoute
  '/app/ai': typeof AppAiRoute
  '/app/baocao': typeof AppBaocaoRoute
  '/app/canhbao': typeof AppCanhbaoRoute
  '/app/hoachat': typeof AppHoachatRoute
  '/app/nguong': typeof AppNguongRoute
  '/app/nhatky': typeof AppNhatkyRoute
  '/app/nhatky-so': typeof AppNhatkySoRoute
  '/app/quantri': typeof AppQuantriRoute
  '/app/theodoi': typeof AppTheodoiRoute
  '/app/thietbi': typeof AppThietbiRoute
  '/app/trienkhai': typeof AppTrienkhaiRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/luu-luong'
    | '/app/ai'
    | '/app/baocao'
    | '/app/canhbao'
    | '/app/hoachat'
    | '/app/nguong'
    | '/app/nhatky'
    | '/app/nhatky-so'
    | '/app/quantri'
    | '/app/theodoi'
    | '/app/thietbi'
    | '/app/trienkhai'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/luu-luong'
    | '/app/ai'
    | '/app/baocao'
    | '/app/canhbao'
    | '/app/hoachat'
    | '/app/nguong'
    | '/app/nhatky'
    | '/app/nhatky-so'
    | '/app/quantri'
    | '/app/theodoi'
    | '/app/thietbi'
    | '/app/trienkhai'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/luu-luong'
    | '/app/ai'
    | '/app/baocao'
    | '/app/canhbao'
    | '/app/hoachat'
    | '/app/nguong'
    | '/app/nhatky'
    | '/app/nhatky-so'
    | '/app/quantri'
    | '/app/theodoi'
    | '/app/thietbi'
    | '/app/trienkhai'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiLuuLuongRoute: typeof ApiLuuLuongRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/luu-luong': {
      id: '/api/luu-luong'
      path: '/api/luu-luong'
      fullPath: '/api/luu-luong'
      preLoaderRoute: typeof ApiLuuLuongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/baocao': {
      id: '/app/baocao'
      path: '/baocao'
      fullPath: '/app/baocao'
      preLoaderRoute: typeof AppBaocaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/canhbao': {
      id: '/app/canhbao'
      path: '/canhbao'
      fullPath: '/app/canhbao'
      preLoaderRoute: typeof AppCanhbaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hoachat': {
      id: '/app/hoachat'
      path: '/hoachat'
      fullPath: '/app/hoachat'
      preLoaderRoute: typeof AppHoachatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nguong': {
      id: '/app/nguong'
      path: '/nguong'
      fullPath: '/app/nguong'
      preLoaderRoute: typeof AppNguongRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nhatky': {
      id: '/app/nhatky'
      path: '/nhatky'
      fullPath: '/app/nhatky'
      preLoaderRoute: typeof AppNhatkyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nhatky-so': {
      id: '/app/nhatky-so'
      path: '/nhatky-so'
      fullPath: '/app/nhatky-so'
      preLoaderRoute: typeof AppNhatkySoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quantri': {
      id: '/app/quantri'
      path: '/quantri'
      fullPath: '/app/quantri'
      preLoaderRoute: typeof AppQuantriRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/theodoi': {
      id: '/app/theodoi'
      path: '/theodoi'
      fullPath: '/app/theodoi'
      preLoaderRoute: typeof AppTheodoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/thietbi': {
      id: '/app/thietbi'
      path: '/thietbi'
      fullPath: '/app/thietbi'
      preLoaderRoute: typeof AppThietbiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trienkhai': {
      id: '/app/trienkhai'
      path: '/trienkhai'
      fullPath: '/app/trienkhai'
      preLoaderRoute: typeof AppTrienkhaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBaocaoRoute: typeof AppBaocaoRoute
  AppCanhbaoRoute: typeof AppCanhbaoRoute
  AppHoachatRoute: typeof AppHoachatRoute
  AppNguongRoute: typeof AppNguongRoute
  AppNhatkyRoute: typeof AppNhatkyRoute
  AppNhatkySoRoute: typeof AppNhatkySoRoute
  AppQuantriRoute: typeof AppQuantriRoute
  AppTheodoiRoute: typeof AppTheodoiRoute
  AppThietbiRoute: typeof AppThietbiRoute
  AppTrienkhaiRoute: typeof AppTrienkhaiRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBaocaoRoute: AppBaocaoRoute,
  AppCanhbaoRoute: AppCanhbaoRoute,
  AppHoachatRoute: AppHoachatRoute,
  AppNguongRoute: AppNguongRoute,
  AppNhatkyRoute: AppNhatkyRoute,
  AppNhatkySoRoute: AppNhatkySoRoute,
  AppQuantriRoute: AppQuantriRoute,
  AppTheodoiRoute: AppTheodoiRoute,
  AppThietbiRoute: AppThietbiRoute,
  AppTrienkhaiRoute: AppTrienkhaiRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiLuuLuongRoute: ApiLuuLuongRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
